import { test, expect } from "../fixtures/auth";
import { signedInClient } from "../fixtures/supabaseClient";

/**
 * What a client may see (feature 011 / contracts/client-facing-artifact.md).
 *
 * The proposal here is seeded to look like one generated BEFORE the redaction shipped:
 * its stored artifact carries the price band, the methodology link and a sign-in email,
 * and it has no `contactEmailIsPublic` marker. That is the case the contract is really
 * about — redaction happens at render, so proposals already in the database stop leaking
 * without being rewritten. A proposal generated today would have nothing to strip.
 *
 * Runs anonymous: this is the view an outside visitor gets from the share link.
 */
test.use({ storageState: { cookies: [], origins: [] } });

// Deliberately share no digit sequence with each other: 54,321 contains "4,321", so a
// floor of 4321 would "leak" through the quote and fail the assertion for the wrong reason.
const FLOOR = 1777;
const CEILING = 98652;
const QUOTE = 54321;
const LOGIN_EMAIL = "seeded-login-address@example.com";
const RIZQ_TAGLINE = "سعّر بثقة. اقبض رزقك.";

let token: string;
let proposalId: string;

test.beforeAll(async () => {
  const { client, userId } = await signedInClient("main");

  const [{ data: specialty }, { data: city }, { data: tier }] = await Promise.all([
    client.from("specialties").select("id").limit(1).single(),
    client.from("cities").select("id").limit(1).single(),
    client.from("experience_tiers").select("id").limit(1).single(),
  ]);
  if (!specialty || !city || !tier) throw new Error("reference data missing — cannot seed");

  token = `e2eredaction${Date.now()}${Math.floor(Math.random() * 1e6)}`;

  // A legacy-shaped artifact: every field the contract withholds is present in storage.
  const artifact = {
    sections: [
      {
        id: "cover",
        order: 1,
        editable: false,
        aiEditable: false,
        content: {
          projectTitle: "E2E redaction probe",
          clientName: "E2E Client",
          brandName: "E2E Freelancer",
          tagline: RIZQ_TAGLINE,
          contact: { email: LOGIN_EMAIL, phone: null, whatsapp: null },
          // NO contactEmailIsPublic marker → predates the contact_email-only rule.
        },
      },
      {
        id: "pricing",
        order: 7,
        editable: true,
        aiEditable: false,
        content: {
          min: FLOOR,
          anchor: QUOTE,
          max: CEILING,
          sampleSize: 5,
          citation: "Rizq estimate based on 5 records (published references) to 2026.",
          depositPct: 50,
          methodologyHref: "/methodology",
        },
      },
      {
        id: "verification",
        order: 13,
        editable: false,
        aiEditable: false,
        content: {
          proposalId: "RZQ-E2ESEED",
          label: "Generated by Rizq, Saudi Freelancer OS",
          methodologyHref: "/methodology",
        },
      },
    ],
  };

  const { data, error } = await client
    .from("proposals")
    .insert({
      user_id: userId,
      brief_text: "e2e redaction seed",
      scope_json: {},
      extraction_model: "e2e-seed",
      specialty_id: specialty.id,
      city_id: city.id,
      experience_tier_id: tier.id,
      price_min: FLOOR,
      price_anchor: QUOTE,
      price_max: CEILING,
      sample_size: 5,
      dominant_provenance: "published_ref",
      provenance_citation: "e2e seed",
      artifact_json: artifact,
      // The share RPC serves public_share = true AND status <> 'draft'.
      status: "sent",
      public_share: true,
      share_token: token,
    })
    .select("id")
    .single();
  if (error || !data) throw new Error(`could not seed proposal: ${error?.message}`);
  proposalId = data.id as string;
});

test.afterAll(async () => {
  if (!proposalId) return;
  const { client } = await signedInClient("main");
  await client.from("proposals").delete().eq("id", proposalId);
});

test("the shared proposal withholds the band, the login email and Rizq's tagline", async ({
  page,
}) => {
  const res = await page.goto(`/ar/p/${token}`, { waitUntil: "domcontentloaded" });
  expect(res?.status(), "share link resolves").toBeLessThan(400);

  // It really is the proposal, not a not-found page.
  await expect(page.locator("body")).toContainText("E2E redaction probe", { timeout: 15_000 });

  // Everything below is asserted against the SERVED HTML, so a value merely hidden with CSS
  // would still fail — the contract is about not sending it, not about not showing it.
  const html = await page.content();
  const digitsOf = (n: number) => [
    String(n),
    new Intl.NumberFormat("ar-SA").format(n),
    new Intl.NumberFormat("en-US").format(n),
  ];

  for (const form of digitsOf(FLOOR)) {
    expect(html, "price floor must not reach the client").not.toContain(form);
  }
  for (const form of digitsOf(CEILING)) {
    expect(html, "price ceiling must not reach the client").not.toContain(form);
  }
  expect(html, "the sign-in address must not reach the client").not.toContain(LOGIN_EMAIL);
  expect(html, "the pricing methodology is internal decision support").not.toMatch(
    /href="[^"]*\/methodology/,
  );

  // The tagline is checked against the rendered document rather than the raw HTML: the
  // page ships the whole next-intl catalogue in its RSC payload, and Rizq's own marketing
  // tagline lives in there as site copy. What matters is that it is not presented as this
  // freelancer's tagline on their proposal.
  const artifact = await page.locator("#proposal-artifact").innerText();
  expect(artifact, "Rizq's tagline is not the freelancer's").not.toContain(RIZQ_TAGLINE);
});

test("the shared proposal still carries the quote and its provenance", async ({ page }) => {
  await page.goto(`/ar/p/${token}`, { waitUntil: "domcontentloaded" });
  const html = await page.content();

  // The offer itself and what justifies it are the point of the document (FR-006/FR-007).
  const quoteShown = [String(QUOTE), new Intl.NumberFormat("ar-SA").format(QUOTE)].some((f) =>
    html.includes(f),
  );
  expect(quoteShown, "the quoted price must still be shown").toBe(true);
  await expect(page.locator("body")).toContainText(/published references|مراجع منشورة|سجلات/);
});
