onlyBuiltDependencies:
  - sharp
  - "@parcel/watcher"
  - "@swc/core"
  - unrs-resolver
  - msw
ignoredBuiltDependencies:
  - "@sentry/cli"
  - core-js
  - protobufjs
allowBuilds:
  "@sentry/cli": false
  core-js: false
  protobufjs: false
