/**
 * Per-axis feedback. Without it the loop is blind: it can tell you it ran, not whether the
 * running was worth it.
 *
 * The question this answers is which axis VALUES are ripe and which are spent — is
 * `metamorphic` still producing, has `rusher` been driven enough to trust, did `csv-export`
 * ever find anything. That is what decides where to spend the next run, and when a value has
 * earned retirement.
 *
 * One JSON object per run, appended to `runs.jsonl` and committed. Markdown prose is for
 * people; this is the record the scoreboard is computed from, so it has to survive editing.
 */
import { appendFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { AXIS_NAMES, AXES } from "./axes.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
export const RUNS = resolve(HERE, "runs.jsonl");

/**
 * Record one run.
 *
 * `findings` are what this run OPENED, each `{ text, severity }` with severity P1/P2/P3.
 * `closed` are finding texts this run FIXED — usually ones an earlier run opened, which is how
 * a value's closure rate becomes visible rather than assumed.
 */
export function recordRun({ run, findings = [], closed = [], notes = "" }) {
  const entry = {
    at: new Date().toISOString(),
    run,
    findings: findings.map((f) => (typeof f === "string" ? { text: f, severity: "P3" } : f)),
    closed,
    notes,
  };
  appendFileSync(RUNS, JSON.stringify(entry) + "\n");
  return entry;
}

export function readRuns() {
  if (!existsSync(RUNS)) return [];
  return readFileSync(RUNS, "utf8")
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

const DAY = 24 * 60 * 60 * 1000;

/**
 * Stats for every value of every axis.
 *
 * `yield` is findings per run — the number that says whether this value is still paying for
 * the time it costs. `dryStreak` is how many runs since it last found anything, which is the
 * maturity signal: a value with a long dry streak and a lot of runs behind it is field-tested;
 * one with a long dry streak and three runs behind it is just untested.
 */
export function scoreboard({ now = Date.now() } = {}) {
  const runs = readRuns();
  const stats = {};

  for (const axis of AXIS_NAMES) {
    stats[axis] = {};
    for (const value of AXES[axis].values) {
      stats[axis][value] = {
        runs: 0,
        p1: 0,
        p2: 0,
        p3: 0,
        closed: 0,
        lastRun: null,
        lastFinding: null,
        dryStreak: 0,
      };
    }
  }

  for (const entry of runs) {
    for (const axis of AXIS_NAMES) {
      const value = entry.run?.[axis];
      const cell = stats[axis]?.[value];
      if (!cell) continue;
      cell.runs += 1;
      cell.lastRun = entry.at;
      for (const f of entry.findings) {
        if (f.severity === "P1") cell.p1 += 1;
        else if (f.severity === "P2") cell.p2 += 1;
        else cell.p3 += 1;
        cell.lastFinding = entry.at;
      }
      cell.closed += entry.closed.length;
      cell.dryStreak = entry.findings.length ? 0 : cell.dryStreak + 1;
    }
  }

  for (const axis of AXIS_NAMES) {
    for (const [, cell] of Object.entries(stats[axis])) {
      const found = cell.p1 + cell.p2 + cell.p3;
      cell.found = found;
      cell.yield = cell.runs ? +(found / cell.runs).toFixed(2) : 0;
      // No per-value "open" count: a run credits its closures to every value it carried, so
      // found-minus-closed goes negative the moment a run fixes what an earlier one opened.
      // Open findings are a property of the ledger, not of an axis value.
      cell.daysSinceFinding = cell.lastFinding ? Math.floor((now - Date.parse(cell.lastFinding)) / DAY) : null;
      cell.verdict = verdictFor(cell);
    }
  }

  return stats;
}

/**
 * What to do with this value next.
 *
 * Deliberately blunt, because the point is a decision: burn it more, leave it alone, or stop
 * spending runs on it. "untested" is not the same as "clean" — the distinction the whole
 * scoreboard exists to make.
 */
function verdictFor(cell) {
  if (cell.runs === 0) return "untested";
  if (cell.runs < 3) return "thin — not enough runs to trust";
  if (cell.yield >= 1) return "fertile — burn it more";
  if (cell.yield >= 0.34) return "productive";
  if (cell.dryStreak >= 5) return "mature — consider retiring";
  return "cooling";
}

/** The scoreboard as markdown, ordered so the fertile and the untested stand out. */
export function renderScoreboard(stats = scoreboard()) {
  const runs = readRuns();
  const lines = [
    "# Axis scoreboard",
    "",
    "Generated by `node drive/scoreboard.mjs` from `drive/runs.jsonl`. Do not hand-edit.",
    "",
    `**${runs.length} run(s) recorded.** A value with a long dry streak and many runs behind it is`,
    "field-tested; the same streak with two runs behind it is merely untested. That difference is",
    "the reason this file exists.",
    "",
    "`yield` = findings per run · `dry` = runs since this value last found anything ·",
    "`fixes landed` = defects closed during runs carrying this value, wherever they were opened",
    "",
  ];

  for (const axis of AXIS_NAMES) {
    lines.push(`## ${axis}`, "", `_${AXES[axis].why}_`, "");
    lines.push("| value | runs | P1 | P2 | P3 | fixes landed | yield | dry | last finding | verdict |");
    lines.push("|---|---|---|---|---|---|---|---|---|---|");
    const rows = Object.entries(stats[axis]).sort((a, b) => b[1].yield - a[1].yield || b[1].runs - a[1].runs);
    for (const [value, c] of rows) {
      const last = c.daysSinceFinding == null ? "—" : c.daysSinceFinding === 0 ? "today" : `${c.daysSinceFinding}d ago`;
      lines.push(
        `| \`${value}\` | ${c.runs} | ${c.p1} | ${c.p2} | ${c.p3} | ${c.closed} | ${c.yield} | ${c.dryStreak} | ${last} | ${c.verdict} |`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

/** The values most worth a run next — highest yield first, then anything never tried. */
export function recommendations(stats = scoreboard()) {
  const fertile = [];
  const untested = [];
  for (const axis of AXIS_NAMES) {
    for (const [value, cell] of Object.entries(stats[axis])) {
      if (cell.runs === 0) untested.push(`${axis}=${value}`);
      else if (cell.yield >= 1) fertile.push(`${axis}=${value} (yield ${cell.yield})`);
    }
  }
  return { fertile, untested };
}
